## R libraries

```{r}
library(V8)
library(reshape2)
library(ggplot2)
```

## JS libraries

```{r}
ct <- new_context()
numeric <- ct$source("js/numeric-1.2.6.js")
mathmodels <- ct$source("js/mathmodels.js")
```

## Models

### SI model

```{r}
si.out <- ct$call("mathmodels.si",list(0.99,0.01),list(1),0,20,100)
si.out.long <- melt(si.out,id.vars=c("t"))
ggplot(data=si.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### SIR model

```{r}
sir.out <- ct$call("mathmodels.sir",list(0.99,0.01,0),list(1,0.1),0,20,100)
sir.out.long <- melt(sir.out,id.vars=c("t"))
ggplot(data=sir.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### Levins metapopulation model

```{r}
levins.out <- ct$call("mathmodels.levins",list(0.01),list(1,0.1),0,20,100)
levins.out.long <- melt(levins.out,id.vars=c("t"))
ggplot(data=levins.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### Tilman (1994) metapopulation competition model

```{r}
tilman94.out <- ct$call("mathmodels.tilman94",list(0.01,0.01),list(0.2,0.1,0.8,0.1),0,100,1000)
tilman94.out.long <- melt(tilman94.out,id.vars=c("t"))
ggplot(data=tilman94.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### Lotka-Volterra predator-prey

```{r}
predprey.out <- ct$call("mathmodels.predprey",list(0.5,0.1),list(1.5,1,1,1),0,20,100)
predprey.out.long <- melt(predprey.out,id.vars=c("t"))
ggplot(data=predprey.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### Lotka-Volterra competition

```{r}
lvcompetition.out <- ct$call("mathmodels.lvcompetition",list(10,10),list(0.2,0.1,100,0.5,0.1,100),0,100,100)
lvcompetition.out.long <- melt(lvcompetition.out,id.vars=c("t"))
ggplot(data=lvcompetition.out.long,aes(x=t,y=value,colour=variable))+geom_line()
```

### Logistic growth

```{r}
logisticgrowth.out <- ct$call("mathmodels.logisticgrowth",list(1),list(1,500),0,20,100)
ggplot(data=logisticgrowth.out)+geom_line(aes(x=t,y=y))
```


### Logistic map

```{r}
logisticmap.out <-  ct$call("mathmodels.logisticmap",list(0.1),list(4),101)
ggplot(data=logisticmap.out)+geom_line(aes(x=t,y=y))
```


### Hysteresis

```{r}
hysteresis.out1 <- ct$call("mathmodels.hysteresis",list(1),list(1.0,0.1,3.0,8.0,17),0,500,1000)
hysteresis.out2 <- ct$call("mathmodels.hysteresis",list(12),list(1.0,0.1,3.0,8.0,17),0,500,1000)
hysteresis.out3 <- ct$call("mathmodels.hysteresis",list(15),list(1.0,0.1,3.0,8.0,17),0,500,1000)
hysteresis <- rbind(hysteresis.out1,hysteresis.out2,hysteresis.out3)
hysteresis$Initial <- as.factor(rep(c(1,12,15),each=1000))
ggplot(aes(x=t,y=x,color=Initial),data=hysteresis)+geom_line()
```

